security:
    encoders:
        ShopBundle\Entity\Users:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity: { class: ShopBundle:Users, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /logout
                target: /login
                invalidate_session:   true
                delete_cookies:
                    cost:
                        path:     null
                        domain:   null
            security: true
            anonymous: true
#            access_denied_handler: ShopBundle/Controller/AccessDeniedHandler

    access_control:
        - { path: /admin/.*, role: ROLE_MANAGER }
        - { path: /room, role: IS_AUTHENTICATED_FULLY }
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER]