services:
#    shop_bundle.repository.shop:
#        class: ShopBundle\Repository\ShopRepository
##        factory: ["@doctrine", getRepository]
#        arguments: ["@doctrine", "@class"]
#        calls:
#            - [ setContainer, [ '@service_container' ] ]
